---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  namespace: openstack
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: ceph
    daemon: mon
spec:
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: ceph
    daemon: mon
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ceph-demo
  namespace: openstack
spec:
  selector:
    matchLabels:
      app: ceph-demo
    serviceName: "ceph"
  template:
    metadata:
      labels:
        app: ceph-demo
    spec:
      serviceAccount: openstack-priv
      serviceAccountName: openstack-priv
      nodeSelector:
          "controller": "true"
      containers:
      - name: kraken
        args: ["demo"]
        env:
        - name: CEPH_DEMO_UID
          value: "kubevirt"
        - name: CEPH_DEMO_ACCESS_KEY
          value: "kubevirt"
        - name: CEPH_DEMO_SECRET_KEY
          value: "kubevirt"
        - name: CEPH_DEMO_BUCKET
          value: "kubevirt"
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CEPH_PUBLIC_NETWORK
          value: "0.0.0.0/0"
        image: ceph/demo
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlib
          mountPath: /var/lib/ceph
        - name: etc
          mountPath: /etc/ceph
      volumes:
      - name: varlib
        hostPath:
          path: /var/lib/ceph
      - name: etc
        hostPath:
          path: /etc/ceph
